FROM ubuntu:18.04 as generator

RUN apt update && apt install -y wget
RUN wget -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.83.1/hugo_extended_0.83.1_Linux-64bit.deb && \
    apt install ./hugo.deb && \
    rm hugo.deb

COPY . .
RUN hugo

FROM nginx:alpine

COPY --from=generator ./public /www
COPY default.conf /usr/share/nginx/
CMD ["nginx", "-g", "daemon off;"]
